### ISSUE TITLE
REMOTE COMMAND is not quite working

### ISSUE THREAD

**Issue by bdougie** [DavidWells/markdown-magic#17]
Hi, I am trying to conduct a little test with some Netlify documentation. I have the following in my README.md

I am simply trying to add docs from netlify/netlify-cms to the netlify/netlify-cms-www

Any insight how to accomplish this would be greatly appreciated.

My commit/attempt is here. https://github.com/netlify/netlify-cms-www/commit/39b88920681a07545afea4dc76e5c38bace536c1

**Comment by DavidWells** [comment]
It looks like you are linking to the github page rather than the raw file in github.

If you link to the RAW file it should fix that.

Or it would be cool if markdown magic detected that and automatically pulled in the raw file :)

**Comment by bdougie** [comment]
Oh, I also changed the `source` to `url`.

```
<!-- AUTO-GENERATED-CONTENT:START (REMOTE:url=https://raw.githubusercontent.com/netlify/netlify-cms/master/README.md) -->
```
