### ISSUE TITLE
hosted version of markdownmagic

### ISSUE THREAD

**Issue by tsiq-swyx** [DavidWells/markdown-magic#31]
i know this is outside of mdmagic's domain but i wanted a lighter TOC generator (one where you can just copy and paste and process the TOC in-browser) and markdown magic would have been perfect for this with a few tweaks. so i tried adapting it [here](https://github.com/sw-yx/markdown-magic-hosted/commit/05e1205fad9480e2b4eb032c1903d84a3fa70e18) but wasnt able to fully remove all the fs dependencies in the time i had. just wanted to share this idea in case its something others are also looking for.

**Comment by tsiq-swyx** [comment]
(what i want is something like this: https://ecotrust-canada.github.io/markdown-toc/ ) but better.

**Comment by DavidWells** [comment]
This is a cool idea =)
