### ISSUE TITLE
shortant MATCHWORD

### ISSUE THREAD

**Issue by rjoydip** [DavidWells/markdown-magic#35]
This is not so much important but it could better to make `MATCHWORD` short. Like >> `AUTO-GENERATED-CONTENT` to `AGC` or `~~`

## Example:

```md
<!-- AGC:START (CODE:src=./relative/path/to/code.js) -->
This content will be dynamically replaced with code from the file
<!-- AGC:END -->
```
or

```md
<!-- ~~:START (CODE:src=./relative/path/to/code.js) -->
This content will be dynamically replaced with code from the file
<!-- ~~:END -->
```

**Comment by DavidWells** [comment]
You can customize the `matchword` to anything you'd like via the config object.

Here is an example https://github.com/DavidWells/markdown-magic/blob/master/examples/generate-readme.js#L7
