### ISSUE TITLE
Markdown comments are not used.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [DavidWells/markdown-magic#40]
The comments used by markdown-magic are visible when converting to PDF, for example using pandoc.

Shouldn't real markdown comments be used?  For example [this](https://stackoverflow.com/questions/4823468/comments-in-markdown)?

**Comment by DavidWells** [comment]
Not sure about this one. 

The blocks are how everything works.

You can strip out the comments after processing like so: https://github.com/DavidWells/serverless-workshop/blob/master/postDocs.js#L12

Just make sure you output the markdown files to a different output directory so you don't remove the original comments 😁
