### ISSUE TITLE
Allow maxdepth option in TOC

### ISSUE THREAD

**Issue by katacarbix** [DavidWells/markdown-magic#45]
As far as I can tell, adding the `maxdepth` option to the TOC transform options does nothing. I would expect it to do what it does in [`markdown-toc`](https://github.com/jonschlinkert/markdown-toc#optionsmaxdepth).

There may be other options that are missing as well which would need further testing to find.

**Comment by DavidWells** [comment]
Yeah this doesn't look like its wired up https://github.com/DavidWells/markdown-magic/blob/master/lib/transforms/toc.js#L7-L13

Do you know what the correct setting should be?

**Comment by katacarbix** [comment]
[Here's the list of options](https://github.com/jonschlinkert/markdown-toc#options) for markdown-toc, if that's what you mean.

**Comment by DavidWells** [comment]
Added with `markdown-magic@2.3.0`
