### ISSUE TITLE
Optional syntax with CODE transform is not detected when using lines

### ISSUE THREAD

**Issue by TomPeirs** [DavidWells/markdown-magic#48]
When using the optional parameter lines, then the optional syntax will not be interepreted anymore and no syntax will be placed. I would expect ` ```js ... ` in the example below but nothing happens.
```
<!-- AUTO-GENERATED-CONTENT:START (CODE:src=./relative/path/to/code.js&lines=22-44) -->
This content will be dynamically replaced with code from the file lines 22 through 44
<!-- AUTO-GENERATED-CONTENT:END -->
```

Docu states: syntax (optional): Syntax will be inferred by fileType if not specified

**Comment by forresst** [comment]
I did a test it seems to work fine. 

The `lines`  option has been added in version 2.0.0. What version of markdown-magic do you have?

**Comment by TomPeirs** [comment]
I have  2.0.0. the lines are interpretted for me but the syntax not. I will redeploy this afternoon, and verify if something changed.

**Comment by TomPeirs** [comment]
Apologies, there seems to be an issue with my setup. This ticket is unrelated
