### ISSUE TITLE
How to get local file like (REMOTE)?

### ISSUE THREAD

**Issue by alexd73** [DavidWells/markdown-magic#53]
Can I get a local file like (REMOTE)?
such as `(REMOTE:src=./local/path/to/file.md)`

**Comment by DavidWells** [comment]
Yep! Use the CODE transform https://github.com/DavidWells/markdown-magic#-code

**Comment by alexd73** [comment]
@DavidWells thank you!

I have tried the CODE transform, but it surrounds the content in this symbols ``` 
I would like to insert a formatted Markdown

**Comment by DavidWells** [comment]
Aha, good call!

I've added the `FILE` transform to allow for grabbing in local files without the code blocks in `markdown-magic@2.5.0`

```md
<!-- AUTO-GENERATED-CONTENT:START (FILE:src=./local-file.md) -->
will be replaced by contents of local-file.md
<!-- AUTO-GENERATED-CONTENT:END -->
```
